// src/js/constants/action-types.js

// messages in snackbar
export const DO_SNACK = "DO_SNACK";
export const DO_SNACK_ERROR = "DO_SNACK_ERROR"

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const DELETE_ACCESS_TOKEN = "DELETE_ACCESS_TOKEN";
export const TEST_CONNECTION = "TEST_CONNECTION";
export const LOGOUT = 'LOGOUT';
export const SET_BATCH_ERROR = "SET_BATCH_ERROR";

export const SET_BANK = 'SET_BANK';

export const SET_CONTACTS_NEW = 'SET_CONTACTS_NEW';
export const SET_PAYMENTS_NEW = 'SET_PAYMENTS_NEW';
export const RESET_PAYMENTS_NEW = 'RESET_PAYMENTS_NEW';
export const SET_ACCOUNTS_NEW = 'SET_ACCOUNTS_NEW';
export const SET_RECEIPTS = 'SET_RECEIPTS';
export const SET_PURCHASE_INVOICES = 'SET_PURCHASE_INVOICES';
export const SET_LEDGERS_NEW = 'SET_LEDGERS_NEW';
export const SET_INCOMING_LEDGER_NEW = 'SET_INCOMING_LEDGER_NEW';
export const NOTIFY = 'NOTIFY';
export const SET_CONTACT_KEYWORDS = 'SET_CONTACT_KEYWORDS';
export const SET_CUSTOM_FIELDS_NEW = 'SET_CUSTOM_FIELDS_NEW';
export const SET_PAY_CONNECT = 'SET_PAY_CONNECT';

export const SET_REVENUE_CONFIG = 'SET_REVENUE_CONFIG';
export const SET_REVENUE_CONFIG_UPDATE = 'SET_REVENUE_CONFIG_UPDATE';
export const SET_REVENUE_CONFIG_MANUAL = 'SET_REVENUE_CONFIG_MANUAL';
export const DEL_REVENUE_CONFIG_MANUAL = 'DEL_REVENUE_CONFIG_MANUAL';

export const SET_INCOMING_SUMS = "SET_INCOMING_SUMS";
export const SET_EXPORT_PENDING = "SET_EXPORT_PENDING";
export const SET_OPT_DELETED = 'SET_OPT_DELETED';
export const SET_SYNC_PENDING = 'SET_SYNC_PENDING';

export const SET_BATCH_MSG = "SET_BATCH_MSG";
export const CLEAR_BATCH_MSG = "CLEAR_BATCH_MSG";

export const SET_COUNT = "SET_COUNT";

